name: Clang Format Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clang-format lint
        run: |
          find src include -type f \( -name "*.c" -o -name "*.h" \) | xargs -r clang-format --dry-run --Werror
